name: weight_monitoring_app
description: A new Flutter project to monitor weight.

# The following line prevents the package from being accidentally published to pub.dev
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.14.0
  http: ^1.2.2
  intl: ^0.18.0
  firebase_database: ^10.0.11
  package_info_plus: ^8.1.2 
  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
